<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>

    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Application -->
    <AssemblyName>DiscordPresence</AssemblyName>
    <RootNamespace>DiscordPresence</RootNamespace>
    <ApplicationIcon>icon.ico</ApplicationIcon>

    <!-- Metadata -->
    <AssemblyTitle>Discord Presence</AssemblyTitle>
    <Product>Discord Presence</Product>
    <Description>
      Automatic Discord Rich Presence for supported desktop applications.
    </Description>

  <Company>Aurelia Team</Company>
  <Authors>l1near</Authors>
  <Copyright>Copyright © 2026 Aurelia Team</Copyright>

    <!-- Version -->
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>

    <!-- Publish -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <!-- Include .NET runtime -->
    <SelfContained>true</SelfContained>

    <!-- Keep dependencies as separate files -->
    <PublishSingleFile>false</PublishSingleFile>

    <!-- Avoid trimming compatibility issues -->
    <PublishTrimmed>false</PublishTrimmed>

    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>

    <!-- Release -->
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference
      Include="DiscordRichPresence"
      Version="1.6.1.70" />
  </ItemGroup>

</Project>