#nullable enable
namespace DiscordPresence;

partial class GameOverridesForm
{
    private System.ComponentModel.IContainer components = null!;
    private System.Windows.Forms.Panel _headerPanel = null!;
    private System.Windows.Forms.PictureBox _headerIcon = null!;
    private System.Windows.Forms.Label _titleLabel = null!;
    private System.Windows.Forms.Label _subtitleLabel = null!;
    private System.Windows.Forms.Label _includedLabel = null!;
    private System.Windows.Forms.Label _excludedLabel = null!;
    private System.Windows.Forms.ListBox _includedList = null!;
    private System.Windows.Forms.ListBox _excludedList = null!;
    private System.Windows.Forms.Button _moveSelectedButton = null!;
    private System.Windows.Forms.Button _removeIncludedButton = null!;
    private System.Windows.Forms.Button _removeExcludedButton = null!;
    private System.Windows.Forms.Label _hintLabel = null!;
    private System.Windows.Forms.Button _clearAllButton = null!;
    private System.Windows.Forms.Button _closeButton = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        _headerPanel = new System.Windows.Forms.Panel();
        _headerIcon = new System.Windows.Forms.PictureBox();
        _titleLabel = new System.Windows.Forms.Label();
        _subtitleLabel = new System.Windows.Forms.Label();
        _includedLabel = new System.Windows.Forms.Label();
        _excludedLabel = new System.Windows.Forms.Label();
        _includedList = new System.Windows.Forms.ListBox();
        _excludedList = new System.Windows.Forms.ListBox();
        _moveSelectedButton = new System.Windows.Forms.Button();
        _removeIncludedButton = new System.Windows.Forms.Button();
        _removeExcludedButton = new System.Windows.Forms.Button();
        _hintLabel = new System.Windows.Forms.Label();
        _clearAllButton = new System.Windows.Forms.Button();
        _closeButton = new System.Windows.Forms.Button();
        ((System.ComponentModel.ISupportInitialize)_headerIcon).BeginInit();
        _headerPanel.SuspendLayout();
        _headerPanel.Name = "_headerPanel";
        _headerPanel.Location = new System.Drawing.Point(16, 16);
        _headerPanel.Size = new System.Drawing.Size(568, 72);
        _headerIcon.Name = "_headerIcon";
        _headerIcon.Location = new System.Drawing.Point(3, 7);
        _headerIcon.Size = new System.Drawing.Size(57, 57);
        _titleLabel.Name = "_titleLabel";
        _titleLabel.Location = new System.Drawing.Point(73, 20);
        _titleLabel.Size = new System.Drawing.Size(130, 13);
        _subtitleLabel.Name = "_subtitleLabel";
        _subtitleLabel.Location = new System.Drawing.Point(73, 36);
        _subtitleLabel.Size = new System.Drawing.Size(238, 28);
        _includedLabel.Name = "_includedLabel";
        _includedLabel.Location = new System.Drawing.Point(16, 104);
        _includedLabel.Size = new System.Drawing.Size(246, 30);
        _excludedLabel.Name = "_excludedLabel";
        _excludedLabel.Location = new System.Drawing.Point(338, 104);
        _excludedLabel.Size = new System.Drawing.Size(246, 30);
        _includedList.Name = "_includedList";
        _includedList.Location = new System.Drawing.Point(16, 134);
        _includedList.Size = new System.Drawing.Size(246, 230);
        _includedList.IntegralHeight = false;
        _includedList.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
        _includedList.BackColor = System.Drawing.Color.White;
        _includedList.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
        _includedList.SelectionMode = System.Windows.Forms.SelectionMode.MultiExtended;
        _excludedList.Name = "_excludedList";
        _excludedList.Location = new System.Drawing.Point(338, 134);
        _excludedList.Size = new System.Drawing.Size(246, 230);
        _excludedList.IntegralHeight = false;
        _excludedList.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
        _excludedList.BackColor = System.Drawing.Color.White;
        _excludedList.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
        _excludedList.SelectionMode = System.Windows.Forms.SelectionMode.MultiExtended;
        _moveSelectedButton.Name = "_moveSelectedButton";
        _moveSelectedButton.Location = new System.Drawing.Point(274, 230);
        _moveSelectedButton.Size = new System.Drawing.Size(52, 36);
        _moveSelectedButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
        _moveSelectedButton.UseVisualStyleBackColor = false;
        _moveSelectedButton.FlatAppearance.BorderSize = 1;
        _moveSelectedButton.Cursor = System.Windows.Forms.Cursors.Hand;
        _removeIncludedButton.Name = "_removeIncludedButton";
        _removeIncludedButton.Location = new System.Drawing.Point(16, 374);
        _removeIncludedButton.Size = new System.Drawing.Size(246, 34);
        _removeIncludedButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
        _removeIncludedButton.UseVisualStyleBackColor = false;
        _removeIncludedButton.FlatAppearance.BorderSize = 1;
        _removeIncludedButton.Cursor = System.Windows.Forms.Cursors.Hand;
        _removeExcludedButton.Name = "_removeExcludedButton";
        _removeExcludedButton.Location = new System.Drawing.Point(338, 374);
        _removeExcludedButton.Size = new System.Drawing.Size(246, 34);
        _removeExcludedButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
        _removeExcludedButton.UseVisualStyleBackColor = false;
        _removeExcludedButton.FlatAppearance.BorderSize = 1;
        _removeExcludedButton.Cursor = System.Windows.Forms.Cursors.Hand;
        _hintLabel.Name = "_hintLabel";
        _hintLabel.Location = new System.Drawing.Point(16, 418);
        _hintLabel.Size = new System.Drawing.Size(568, 22);
        _clearAllButton.Name = "_clearAllButton";
        _clearAllButton.Location = new System.Drawing.Point(16, 450);
        _clearAllButton.Size = new System.Drawing.Size(170, 32);
        _clearAllButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
        _clearAllButton.UseVisualStyleBackColor = false;
        _clearAllButton.FlatAppearance.BorderSize = 1;
        _clearAllButton.Cursor = System.Windows.Forms.Cursors.Hand;
        _closeButton.Name = "_closeButton";
        _closeButton.Location = new System.Drawing.Point(474, 450);
        _closeButton.Size = new System.Drawing.Size(110, 32);
        _closeButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
        _closeButton.UseVisualStyleBackColor = false;
        _closeButton.FlatAppearance.BorderSize = 1;
        _closeButton.Cursor = System.Windows.Forms.Cursors.Hand;
        _titleLabel.Text = "Game detection";
        _subtitleLabel.Text = "Choose which applications are treated as games.";
        _includedLabel.Text = "Always treat as game";
        _excludedLabel.Text = "Never treat as game";
        _moveSelectedButton.Text = "<<";
        _removeIncludedButton.Text = "Remove selected";
        _removeExcludedButton.Text = "Remove selected";
        _hintLabel.Text = "Ctrl / Shift: select multiple. Remove returns to automatic detection.";
        _clearAllButton.Text = "Clear all overrides";
        _closeButton.Text = "Close";
        _headerPanel.BackColor = System.Drawing.Color.FromArgb(241, 245, 249);
        _headerIcon.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
        _headerIcon.TabStop = false;
        _titleLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
        _titleLabel.ForeColor = System.Drawing.Color.FromArgb(88, 101, 242);
        _includedLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
        _includedLabel.ForeColor = System.Drawing.Color.FromArgb(88, 101, 242);
        _excludedLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
        _excludedLabel.ForeColor = System.Drawing.Color.FromArgb(220, 53, 69);
        _subtitleLabel.ForeColor = System.Drawing.Color.FromArgb(100, 116, 139);
        _hintLabel.ForeColor = System.Drawing.Color.FromArgb(100, 116, 139);
        _includedLabel.BackColor = System.Drawing.Color.FromArgb(244, 243, 255);
        _includedLabel.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
        _includedLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
        _excludedLabel.BackColor = System.Drawing.Color.FromArgb(255, 238, 241);
        _excludedLabel.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
        _excludedLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
        _moveSelectedButton.BackColor = System.Drawing.Color.FromArgb(231, 243, 255);
        _moveSelectedButton.ForeColor = System.Drawing.Color.FromArgb(24, 119, 242);
        _moveSelectedButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(24, 119, 242);
        _moveSelectedButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(24, 119, 242);
        _moveSelectedButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(24, 119, 242);
        _removeIncludedButton.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
        _removeIncludedButton.ForeColor = System.Drawing.Color.FromArgb(220, 53, 69);
        _removeIncludedButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(220, 53, 69);
        _removeIncludedButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(220, 53, 69);
        _removeIncludedButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(220, 53, 69);
        _removeExcludedButton.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
        _removeExcludedButton.ForeColor = System.Drawing.Color.FromArgb(220, 53, 69);
        _removeExcludedButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(220, 53, 69);
        _removeExcludedButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(220, 53, 69);
        _removeExcludedButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(220, 53, 69);
        _clearAllButton.BackColor = System.Drawing.Color.FromArgb(255, 238, 241);
        _clearAllButton.ForeColor = System.Drawing.Color.FromArgb(220, 53, 69);
        _clearAllButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(220, 53, 69);
        _clearAllButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(220, 53, 69);
        _clearAllButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(220, 53, 69);
        _closeButton.BackColor = System.Drawing.Color.FromArgb(88, 101, 242);
        _closeButton.ForeColor = System.Drawing.Color.FromArgb(255, 255, 255);
        _closeButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(88, 101, 242);
        _closeButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(71, 82, 196);
        _closeButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(71, 82, 196);
        _includedList.TabIndex = 0;
        _excludedList.TabIndex = 1;
        _moveSelectedButton.TabIndex = 2;
        _removeIncludedButton.TabIndex = 3;
        _removeExcludedButton.TabIndex = 4;
        _clearAllButton.TabIndex = 5;
        _closeButton.TabIndex = 6;
        _moveSelectedButton.Enabled = false;
        _closeButton.DialogResult = System.Windows.Forms.DialogResult.OK;
        AcceptButton = _closeButton;
        CancelButton = _closeButton;
        Controls.Add(_headerPanel);
        _headerPanel.Controls.Add(_headerIcon);
        _headerPanel.Controls.Add(_titleLabel);
        _headerPanel.Controls.Add(_subtitleLabel);
        Controls.Add(_includedLabel);
        Controls.Add(_excludedLabel);
        Controls.Add(_includedList);
        Controls.Add(_excludedList);
        Controls.Add(_moveSelectedButton);
        Controls.Add(_removeIncludedButton);
        Controls.Add(_removeExcludedButton);
        Controls.Add(_hintLabel);
        Controls.Add(_clearAllButton);
        Controls.Add(_closeButton);
        AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
        AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        ClientSize = new System.Drawing.Size(600, 494);
        BackColor = System.Drawing.Color.FromArgb(247, 249, 252);
        ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
        Font = new System.Drawing.Font("Segoe UI", 9F);
        FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        ShowInTaskbar = false;
        StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
        Name = "GameOverridesForm";
        Text = "Manage game";
        ((System.ComponentModel.ISupportInitialize)_headerIcon).EndInit();
        _headerPanel.ResumeLayout(false);
    }
}

